version: "{branch}-{build}"
environment:
 PY_PYTHON: 2.7-32
install:
  - py -m pip install --upgrade pip
  - py -m pip install markdown
  - py -m pip install scons


build_script:
  - cd source
  - scons
  - scons pot

artifacts:
  - path: 'source\*.nvda-addon'
    name: addon
    type: application/x-nvda-addon
  - path: 'source\*.pot'
    type: application/x-pot
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: uK31tp+xqv78Wvxvl5nRI6vBL97we6/8qQHA2YK5mRn2Q40tkikzZbOm9r+otdpR
  artifact: addon
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only
